# Generated by Django 4.2.7 on 2023-11-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='author name', max_length=100, null=True)),
                ('email', models.CharField(blank=True, help_text='author email', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='book name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='book description', null=True)),
                ('image', models.ImageField(blank=True, help_text='book image', null=True, upload_to='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.authormodel')),
            ],
        ),
    ]
